---
title: "data-cleaning"
output: html_document
---

## Variable guide

autoc_support: 0 - does not support; 1 - supports
autoc_support_cat: supports, does not support (use for visualizations)
econ_percep: bad, good


**Note: subset only has 117 observations. Is that because we dropped all NAs? Maybe try reloading the data later and remove the drop.na codes, then see if there are more.**

```{r setup, echo=FALSE}
library(haven)
library(readxl) 
library(tidyverse)
library(ggplot2)
library(forcats)
library(sjmisc)
library(pROC)
```

```{r load-data}
#read the data file
amertrends <- read_sav("data/data-raw/W124_Mar23/ATP W124.sav")

#load the codebook for the data to understand what each variable represents
amertrends_codebook <- read_excel("data/data-raw/W124_Mar23/ATP W124 Codebook.xlsx")
```

```{r create-subset}
#selecting a subset the variables for exploration 
amertrends_subset <- amertrends |> 
  select(POLSYS_AUTOC_W124, ECON_SIT_W124, PARTYFAV_REP_W124, PARTYFAV_DEM_W124, PARTY_REPRESENT_W124, NEWSSOURCE_e_W124, NEWSUSE_PLAT_a_W124, NEWSUSE_PLAT_b_W124, NEWSUSE_PLAT_c_W124, NEWSUSE_PLAT_d_W124, NEWSUSE_PLAT_e_W124, F_AGECAT, F_GENDER, F_EDUCCAT, F_EDUCCAT2, F_HISP, F_HISP_ORIGIN, F_RACECMB, F_RACETHNMOD, F_MARITAL, F_RELIG, F_BORN, F_RELIGCAT1, F_PARTY_FINAL, F_PARTYLN_FINAL, F_PARTYSUM_FINAL, F_PARTYSUMIDEO_FINAL, F_INC_SDT1, F_IDEO, F_INC_TIER2)

#change variable names to snake_case
amertrends_subset <- janitor::clean_names(amertrends_subset)

#converting 99 to NA (99 means "refused"/didn't answer that question so it must be treated as NA)
amertrends_subset <- amertrends_subset |> 
  mutate(across(everything(), ~ replace(.x, .x == 99, NA)))

#visualize missing data in the subset
visdat::vis_miss(amertrends_subset)

#redefine column types to factor since they represent ordered categories/likert scale 
amertrends_subset <- amertrends_subset |> 
  mutate(across(where(is.numeric), as.factor))
```

```{r autoc_support}
#make the response autoc variable binary/logical so it will work in the logistic model
amertrends_subset <- amertrends_subset |> 
  mutate(autoc_support = fct_collapse(polsys_autoc_w124,
                                    `1` = c("1", "2"),
                                    `0` = c("3", "4"))) |> 
  drop_na(autoc_support)

amertrends_subset <- amertrends_subset |> 
  mutate(autoc_support_cat = fct_collapse(polsys_autoc_w124,
                                    `Supports` = c("1", "2"),
                                    `Does not support` = c("3", "4"))) 

#change column type to numeric
#or logical if necessary
#amertrends_subset <- amertrends_subset |> 
  #mutate(autoc_support = as.logical(as.numeric(as.character(autoc_support)))) |> 
  #select(autoc_support)
amertrends_subset <- amertrends_subset |> 
  mutate(autoc_support = as.numeric(as.character(autoc_support))) 
```

```{r econ_perception}
#defining the levels of key explanatory variables
#econ_sit_w124 (may consider collapsing into good/bad rather than keeping 4 levels)
amertrends_subset <- amertrends_subset|> 
  #drop_na(econ_sit_w124) |> 
  mutate(econ_sit_w124 = fct_recode(econ_sit_w124,
                          "very good" = "1",
                          "somewhat good" = "2",
                          "somewhat bad" = "3",
                          "very bad" = "4")) 

#bar chart for econ_sit_w124 shows most are in the somewhat bad/good categories, fewer people chose the extremes
ggplot(amertrends_subset) +
  geom_bar(aes(econ_sit_w124))

#since there are considerably fewer observations at the extremes, collapse econ_sit_w124 into 2 categories: good and bad
amertrends_subset <- amertrends_subset |> 
  mutate(econ_percep = fct_collapse(econ_sit_w124,
                                      good = c("very good", "somewhat good"),
                                      bad = c("very bad", "somewhat bad")))
```

```{r social_media}
#creating social media reliance index variable

#re-coding newsuse variables
#newsuse_plat_a basic facts
amertrends_subset <- amertrends_subset |> 
  #drop_na(newsuse_plat_a_w124) |> 
  mutate(sm_pref_basicfacts = fct_collapse(newsuse_plat_a_w124,
                                      `2` = c("2"),
                                      `1` = c("3"),
                                      `0` = c("1", "4"))) 
#newsuse_plat_b opinions
amertrends_subset <- amertrends_subset |> 
  #drop_na(newsuse_plat_b_w124) |> 
  mutate(sm_pref_opinions = fct_collapse(newsuse_plat_b_w124,
                                      `2` = c("2"),
                                      `1` = c("3"),
                                      `0` = c("1", "4"))) 
#newsuse_plat_c in depth info
amertrends_subset <- amertrends_subset |> 
  #drop_na(newsuse_plat_c_w124) |> 
  mutate(sm_pref_indepth = fct_collapse(newsuse_plat_c_w124,
                                      `2` = c("2"),
                                      `1` = c("3"),
                                      `0` = c("1", "4"))) 
#news_plat_d up to date info
amertrends_subset <- amertrends_subset |> 
  #drop_na(newsuse_plat_d_w124) |> 
  mutate(sm_pref_uptodate = fct_collapse(newsuse_plat_d_w124,
                                      `2` = c("2"),
                                      `1` = c("3"),
                                      `0` = c("1", "4"))) 
#news_plat_e info that impacts the respondent
amertrends_subset <- amertrends_subset |> 
  #drop_na(newsuse_plat_e_w124) |> 
  mutate(sm_pref_impactsr = fct_collapse(newsuse_plat_e_w124,
                                      `2` = c("2"),
                                      `1` = c("3"),
                                      `0` = c("1", "4"))) 

#create the index variable for social media preference
amertrends_subset <- amertrends_subset |> 
  drop_na(sm_pref_basicfacts, sm_pref_opinions, sm_pref_indepth, sm_pref_uptodate, sm_pref_impactsr) |> 
  rowwise() |> 
  mutate(sm_pref_index = sum(as.numeric(as.character(c_across(starts_with("sm_pref_")))))) |> 
  ungroup() 

#re-level newssource_plat_e: how frequently they get their news from social media
amertrends_subset <- amertrends_subset |> 
  mutate(sm_freq = fct_recode(newssource_e_w124, 
                              "5" = "1",
                              "4" = "2",
                              "3" = "3",
                              "2" = "4",
                              "1" = "5"),
         sm_freq = as.numeric(as.character(sm_freq))) 


```


```{r desc-stats}
#age category counts
#recode to more descriptive values
amertrends_subset <- amertrends_subset |> 
  mutate(age = fct_recode(f_agecat,
                          "18-29" = "1",
                          "30-49" = "2",
                          "50-64" = "3",
                          "65+" = "4")) 
#freq table for age
frq(amertrends_subset$age, out = "v")

#recode race to binary 
amertrends_subset <- amertrends_subset |> 
  mutate(race_1 = fct_collapse(f_racecmb,
                          "Non-White" =  c("2", "3", "4", "5"),
                          "White" = "1")) |> 
  mutate(race_1 = fct_relevel(white,
                             "White", after = 1)) 

#freq table for race
frq(amertrends_subset$race_1, out = "v")

#recode party lean
amertrends_subset <- amertrends_subset |> 
  mutate(pol_lean = fct_recode(f_partysum_final,
                          "Republican, or leans Republican" = "1",
                          "Democrat, or leans Democrat" = "2",
                          "Other" = "9"),
         pol_lean = fct_relevel(pol_lean, 
                                "Republican, or leans Republican", after = 1))
  
#freq table for pol party
frq(amertrends_subset$pol_lean, out = "v")

#recode income
amertrends_subset <- amertrends_subset |> 
  mutate(income = fct_recode(f_inc_tier2,
                          "Lower income" = "1",
                          "Middle income" = "2",
                          "Upper income" = "3")) 
#freq table for income
frq(amertrends_subset$income, out = "v")

#freq table for econ perception
frq(amertrends_subset$econ_percep, out = "v")

#freq table for autoc support
#0 = doesn't support
#1 = does support
frq(amertrends_subset$autoc_support_cat, out = "v") 

#boxplot for sm_pref score
amertrends_subset |> 
  ggplot() +
  geom_boxplot(aes(x = sm_pref_index,
                   y = pol_lean),
               fill = "blue4",
               alpha = 0.75) +
  labs(x = "Social Media Preference Index Score",
       y = "Political Leaning") +
  theme_minimal()
#density
ggplot(amertrends_subset) +
  geom_density(aes(x = sm_pref_index,
                   fill = autoc_support_cat), 
               position = "stack", 
               alpha = 0.75) +
  theme_bw() +
  labs(x = "Social Media Preference Index Score",
       y = "Density",
       fill = "Support for Autocratic Leadership",
       title = "Distribution of Social Media Prefence Index Scores") +
  scale_fill_manual(values = c("turquoise3", "blue4")) 

#summary stats for sm_pref_index
summary(amertrends_subset$sm_pref_index)
sd(amertrends_subset$sm_pref_index)
ggplot(amertrends_subset) +
  geom_histogram(aes(x = sm_pref_index))

#newssource
#recoding for desc stats table
amertrends_subset <- amertrends_subset |> 
  mutate(income = fct_recode(f_inc_tier2,
                          "Lower income" = "1",
                          "Middle income" = "2",
                          "Upper income" = "3")) 
amertrends_subset <- amertrends_subset |> 
  mutate(sm_freq_cat = fct_recode(newssource_e_w124, 
                                  "Extremely often" = "5",
                                  "Fairly often" = "4",
                                  "Sometimes" = "3",
                                  "Rarely" = "2",
                                  "Never" = "1")) 
#freq table for sm_freq_cat
frq(amertrends_subset$sm_freq_cat, out = "v")

```

```{r model_v1}
#model v1
autoc_lm_v1 <- glm(autoc_support ~ sm_pref_index + sm_freq + factor(econ_percep) + factor(age) + factor(race_1) + factor(pol_lean)  + factor(pol_lean)*sm_pref_index + factor(income), family = binomial(link = "logit"), data = amertrends_subset)
summary(autoc_lm_v1)
car::vif(autoc_lm_v1)

#ROC curve for v1
#predicted probabilities
predicted_probs_v1 <- predict(autoc_lm_v1, type = "response")
#actual outcomes
actual_outcomes_v1 <- autoc_lm_v1$y
#ROC
roc_v1 <- roc(actual_outcomes_v1, predicted_probs_v1)
#plot the curve
plot(roc_v1, legacy.axes = TRUE, main = "ROC Curve for autoc_lm_v1", 
     col = "blue", xlab = "False Positive Rate (1 - Specificity)", 
     ylab = "True Positive Rate (Sensitivity)")
auc(roc_v1)

```


```{r stepwise}

#drop NA values for all variables used in either model
amertrends_subset <- amertrends_subset |> 
  drop_na(autoc_support, sm_pref_index, sm_freq, econ_percep, age, race_1, pol_lean, income)

# Fit the lower and upper models using the cleaned data
small_v1<- glm(autoc_support ~ sm_pref_index + sm_freq + factor(econ_percep) + factor(pol_lean)*sm_pref_index , family = binomial(link = "logit"), data = clean_data)
big_v1<- glm(autoc_support ~ sm_pref_index + sm_freq + factor(econ_percep) + factor(age) + factor(race_1) + factor(pol_lean) + factor(pol_lean)*sm_pref_index + factor(income), family = binomial(link = "logit"), data = clean_data)
# Stepwise selection
autoc_lm_v2 <- step(big_v1, scope = list(lower = small_v1, upper = big_v1), direction = "both")
#final selected model (based on AIC) includes just race and income as controls

#model parameter estimates and significance testing
summary(autoc_lm_v2)

#ROC curve for v2
#predicted probabilities
predicted_probs_v2 <- predict(autoc_lm_v2, type = "response")
#actual outcomes
actual_outcomes_v2 <- autoc_lm_v2$y
#ROC
roc_v2 <- roc(actual_outcomes_v2, predicted_probs_v2)
#plot the curve
plot(roc_v2, legacy.axes = TRUE, main = "ROC Curve for autoc_lm_v2", 
     col = "blue", xlab = "False Positive Rate (1 - Specificity)", 
     ylab = "True Positive Rate (Sensitivity)")
auc(roc_v2)

```

```{r}
#based on the ANOVA, decide not to include the extra demographic variable age (has three categories, none significant on wald z test)
anova(autoc_lm_v2, autoc_lm_v1, test = "Chisq")
```
```{r}
#write_csv(amertrends_subset, "data/data-clean/amertrends_clean.csv")
```



Removed this from the paper since we need better figures
```{r}
#| echo: FALSE
ggplot(amertrends_subset) +
  geom_density(aes(x = sm_pref_index,
                   fill = autoc_support_cat), 
               position = "stack", 
               alpha = 0.75) +
  theme_bw() +
  labs(x = "Social Media Preference Index Score",
       y = "Density",
       fill = "Support for Autocratic Leadership",
       title = "Distribution of Social Media Prefence Index Scores") +
  scale_fill_manual(values = c("turquoise3", "blue4"))
```
